url: http://www.rszx.org

title: 堡利莱印刷机械

keywords: 堡利莱印刷机械

description: 堡利莱印刷机械。

relative_permalinks: false

address: 广东省佛山市顺德区勒流镇新城第一工业区华城路1号

tel: 0757-29899681

mobile: 13928242943

qq: 542801638

email: info@bristargroup.com.au

exclude:
  - README.md
